1.- Antes de empezar a trabajar con la BBDD de Northwind, conozcamos un poco las BBDD que tenemos en nuestro servidor. ¿Qué BBDD tenemos en nuestro servidor?

In [1]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /home/cassia_d/anaconda3/lib/python3.9/site-packages (8.0.32)
Requirement already satisfied: protobuf<=3.20.3,>=3.11.0 in /home/cassia_d/anaconda3/lib/python3.9/site-packages (from mysql-connector-python) (3.20.3)

In [2]:
import mysql.connector

In [3]:
mydb = mysql.connector.connect(
user='root', 
password='AlumnaAdalab',
host='127.0.0.1',
database='northwind')

In [4]:
cursor = mydb.cursor()

In [5]:
cursor.execute("SHOW DATABASES")

for i in cursor:
    print(i)

('adalab',)
('information_schema',)
('leccion-1-sql',)
('leccion-10-sql',)
('leccion-11-sql',)
('leccion-12-sql',)
('leccion-13-sql',)
('leccion-14-sql',)
('leccion-2-sql',)
('leccion-3-sql',)
('leccion-4-sql',)
('leccion-5-sql',)
('leccion-6-sql',)
('leccion-7-sql',)
('leccion-8-sql',)
('leccion-9-sql',)
('mi_primerita_bbdd_python',)
('musica_adalabers',)
('mysql',)
('northwind',)
('performance_schema',)
('proyecto1',)
('sakila',)
('sports_analytics',)
('sys',)
('tienda',)
('tienda_zapatillas',)
('world',)

2.-Empezemos a explorar la BBDD de Northwind. ¿Qué tablas componen la BBDD? Recuerda que primero nos tendremos que conectar con la BBDD sobre la que queremos trabajar. Guarda el resultado de los nombres de la tablas en una lista.

In [6]:
cursor.execute("SHOW TABLES")

guardado_tabla = []

for i, n in enumerate(cursor):
    print(n[0])
    guardado_tabla.append(n[0])

guardado_tabla

categories
customer_customer_demo
customer_demographics
customers
empleadas
employee_territories
employees
order_details
orders
products
region
shippers
suppliers
territories

['categories',
 'customer_customer_demo',
 'customer_demographics',
 'customers',
 'empleadas',
 'employee_territories',
 'employees',
 'order_details',
 'orders',
 'products',
 'region',
 'shippers',
 'suppliers',
 'territories']

In [7]:
cursor.close()
mydb.close()

3.-¿Qué columnas tiene cada una de las tablas? Para esto tendréis que hacer un for loop para que nos saque el resultado de todas las columnas.

In [8]:
mydb = mysql.connector.connect(
user='root', 
password='AlumnaAdalab',
host='127.0.0.1',
database='INFORMATION_SCHEMA')

In [9]:
cursor = mydb.cursor()

In [10]:
cursor.execute("SELECT * FROM COLUMNS WHERE TABLE_NAME = 'categories'")

4.-Hagamos unas queries facilitas:

Extraed el primer pedido donde se ha gastado más. Devolved el id del pedido y la cantidad gastada.

Devuelve la misma query que en el anterior ejercicio, pero en este caso devuelve todos los resultados.

Extraed el números de pedidos que se hayan hecho por dia. Devuelve los resultados en una dataframe.

Extraer los pedidos hechos por "Nancy Daviolo". Tendréis que hacer una subquery.

In [29]:
mydb = mysql.connector.connect(
user='root', 
password='AlumnaAdalab',
host='127.0.0.1',
database='northwind')

In [30]:
cursor = mydb.cursor()

In [32]:
# Query 1: el primer pedido donde se ha gastado mas

mydb = mysql.connector.connect(
user='root', 
password='AlumnaAdalab',
host='127.0.0.1',
database='northwind')

cursor = mydb.cursor()

query1 = "SELECT order_id, (unit_price*quantity) AS Cantidad_gastada FROM order_details ORDER BY (unit_price*quantity) DESC" 

cursor.execute(query1)

resultado = cursor.fetchone()
resultado

(10865, 15810.0)

In [33]:
# Query 2: todos los pedidos con la cantidad gastada 

mydb = mysql.connector.connect(
user='root', 
password='AlumnaAdalab',
host='127.0.0.1',
database='northwind')

cursor = mydb.cursor()

query2 = "SELECT order_id, (unit_price*quantity) AS Cantidad_gastada FROM order_details ORDER BY (unit_price*quantity) DESC" 

cursor.execute(query2)

resultado2 = cursor.fetchall()
resultado2

[(10865, 15810.0),
 (10981, 15810.0),
 (10353, 10540.0),
 (10417, 10540.0),
 (10889, 10540.0),
 (10424, 10329.2),
 (10897, 9903.2),
 (10372, 8432.0),
 (10540, 7905.0),
 (10816, 7905.0),
 (10817, 7905.0),
 (10912, 7427.400000000001),
 (11030, 7427.400000000001),
 (11032, 6587.5),
 (10776, 6360.0),
 (10479, 6324.0),
 (10993, 6189.5),
 (11017, 6050.0),
 (11030, 5500.0),
 (10515, 5268.0),
 (10691, 4951.6),
 (10687, 4850.0),
 (10510, 4456.4400000000005),
 (10666, 4456.4400000000005),
 (11072, 4322.5),
 (10329, 4216.0),
 (10351, 4216.0),
 (10953, 4050.0),
 (10518, 3952.5),
 (10616, 3952.5),
 (10672, 3952.5),
 (10633, 3944.0),
 (10711, 3935.9999999999995),
 (10607, 3900.0),
 (10678, 3800.0),
 (10360, 3465.0),
 (10595, 3420.0),
 (10895, 3400.0),
 (11008, 3192.0),
 (10514, 3159.0),
 (10634, 3125.0),
 (10854, 3100.0),
 (10267, 3080.0),
 (10430, 3080.0),
 (11064, 3003.0),
 (10893, 2970.96),
 (10949, 2958.0),
 (10515, 2856.0),
 (10324, 2808.0),
 (10524, 2760.0),
 (10316, 2758.0),
 (10841, 2750.0),
 (10688, 2736.0),
 (10694, 2700.0),
 (10514, 2660.0),
 (10561, 2650.0),
 (10479, 2640.0),
 (10490, 2640.0),
 (10805, 2635.0),
 (10252, 2592.0),
 (10549, 2544.0),
 (10588, 2500.0),
 (10629, 2475.8),
 (10787, 2475.8),
 (10801, 2475.8),
 (10305, 2475.0),
 (10745, 2475.0),
 (10852, 2465.0),
 (10605, 2380.0),
 (10440, 2376.0),
 (10691, 2366.3999999999996),
 (10595, 2340.0),
 (10764, 2340.0),
 (11021, 2332.0),
 (10701, 2310.0),
 (10851, 2310.0),
 (10398, 2304.0),
 (10451, 2304.0),
 (11033, 2296.0),
 (10402, 2281.5),
 (10570, 2280.0),
 (10637, 2280.0),
 (10762, 2280.0),
 (10344, 2240.0),
 (10345, 2240.0),
 (10772, 2228.2200000000003),
 (10567, 2200.0),
 (10823, 2200.0),
 (10892, 2200.0),
 (10598, 2195.0),
 (11053, 2187.5),
 (10339, 2184.0),
 (10359, 2176.0),
 (10612, 2170.0),
 (10886, 2170.0),
 (10401, 2128.0),
 (10948, 2120.0),
 (10360, 2108.0),
 (10831, 2108.0),
 (10638, 2088.0),
 (10400, 2079.0),
 (10440, 2052.0),
 (10836, 2040.0),
 (10335, 2035.1999999999998),
 (10332, 2000.0),
 (10369, 1980.0),
 (10546, 1972.0),
 (10988, 1972.0),
 (11021, 1967.49),
 (10601, 1925.0),
 (10703, 1925.0),
 (10372, 1904.0),
 (11030, 1900.0),
 (10990, 1881.0),
 (10789, 1875.0),
 (10658, 1870.0),
 (10691, 1840.0),
 (10395, 1834.0),
 (10384, 1814.3999999999999),
 (10894, 1800.0),
 (10987, 1800.0),
 (10988, 1800.0),
 (11001, 1800.0),
 (10465, 1782.0),
 (10324, 1760.0),
 (10760, 1756.0),
 (10921, 1756.0),
 (10441, 1755.0),
 (10618, 1750.0),
 (10393, 1743.0),
 (10941, 1739.9999999999998),
 (10791, 1733.0600000000002),
 (10971, 1733.0600000000002),
 (10904, 1725.5),
 (10657, 1710.0),
 (10593, 1701.0),
 (10660, 1701.0),
 (10742, 1700.0),
 (11056, 1700.0),
 (10249, 1696.0),
 (10765, 1684.0),
 (10895, 1674.3999999999999),
 (10938, 1666.0),
 (11068, 1656.0),
 (10617, 1650.0),
 (11032, 1650.0),
 (11036, 1650.0),
 (10861, 1638.0),
 (10419, 1632.0),
 (10503, 1627.5),
 (10667, 1620.0),
 (10878, 1620.0),
 (10991, 1620.0),
 (10513, 1600.0),
 (10709, 1600.0),
 (10997, 1600.0),
 (10514, 1596.0),
 (10845, 1596.0),
 (10731, 1590.0),
 (10802, 1590.0),
 (10457, 1584.0),
 (10286, 1576.0),
 (10413, 1576.0),
 (10516, 1562.5),
 (10838, 1562.5),
 (10877, 1562.5),
 (10431, 1560.0),
 (10530, 1560.0),
 (10801, 1560.0),
 (10847, 1560.0),
 (10990, 1560.0),
 (10420, 1552.0),
 (10515, 1552.0),
 (10452, 1550.0),
 (10979, 1536.5),
 (10847, 1530.0),
 (10406, 1528.8),
 (10519, 1520.0),
 (10555, 1520.0),
 (10470, 1500.0),
 (10511, 1500.0),
 (10745, 1500.0),
 (10361, 1496.0),
 (11030, 1494.5),
 (10698, 1485.48),
 (10290, 1485.0),
 (10250, 1484.0),
 (10709, 1484.0),
 (10762, 1484.0),
 (10757, 1479.0),
 (10941, 1479.0),
 (10340, 1472.0),
 (10286, 1440.0),
 (10392, 1440.0),
 (10612, 1440.0),
 (10746, 1440.0),
 (10802, 1440.0),
 (10847, 1440.0),
 (10865, 1440.0),
 (10430, 1404.0),
 (10588, 1400.0),
 (10812, 1392.0),
 (10382, 1386.0),
 (10760, 1380.0),
 (11023, 1380.0),
 (11052, 1380.0),
 (10408, 1379.0),
 (10449, 1379.0),
 (10694, 1375.0),
 (10750, 1375.0),
 (10772, 1375.0),
 (10799, 1375.0),
 (10698, 1368.25),
 (10633, 1368.0),
 (10718, 1368.0),
 (10924, 1368.0),
 (10795, 1365.0),
 (10612, 1360.0),
 (10607, 1350.0),
 (10962, 1350.0),
 (10343, 1330.0),
 (10255, 1320.0),
 (10298, 1320.0),
 (10488, 1320.0),
 (11028, 1320.0),
 (10783, 1317.5),
 (10964, 1317.5),
 (10789, 1317.0),
 (10979, 1317.0),
 (11041, 1317.0),
 (10756, 1312.5),
 (10455, 1310.0),
 (10292, 1296.0),
 (11033, 1296.0),
 (10700, 1290.0),
 (11012, 1290.0),
 (10658, 1288.0),
 (10773, 1287.0),
 (11045, 1272.0),
 (11008, 1260.0),
 (10305, 1250.0),
 (10645, 1250.0),
 (10861, 1250.0),
 (10871, 1250.0),
 (10540, 1249.2),
 (10817, 1249.2),
 (10302, 1248.0),
 (10330, 1245.0),
 (10263, 1242.0),
 (10583, 1237.9),
 (10687, 1237.9),
 (10857, 1237.9),
 (11007, 1237.9),
 (10817, 1232.5),
 (10429, 1228.5),
 (11012, 1224.0),
 (10742, 1218.0),
 (11021, 1218.0),
 (10436, 1216.0),
 (10523, 1215.0),
 (10986, 1215.0),
 (11021, 1215.0),
 (10786, 1200.0),
 (10893, 1200.0),
 (11007, 1200.0),
 (11039, 1200.0),
 (11056, 1200.0),
 (10351, 1193.5),
 (10536, 1190.0),
 (11059, 1190.0),
 (10847, 1182.5),
 (10686, 1170.0),
 (10372, 1167.6000000000001),
 (10796, 1163.75),
 (10678, 1158.0),
 (10461, 1152.0),
 (10530, 1150.0),
 (10526, 1140.0),
 (10543, 1140.0),
 (10547, 1140.0),
 (10712, 1140.0),
 (10755, 1140.0),
 (10820, 1140.0),
 (10841, 1140.0),
 (10968, 1140.0),
 (10795, 1134.25),
 (10566, 1125.0),
 (10346, 1123.2),
 (10985, 1120.0),
 (10804, 1116.0),
 (10325, 1112.0),
 (10459, 1112.0),
 (10258, 1105.0),
 (10641, 1104.0),
 (10706, 1104.0),
 (10817, 1104.0),
 (10938, 1104.0),
 (10339, 1103.2),
 (10511, 1100.0),
 (10527, 1100.0),
 (10533, 1100.0),
 (10605, 1100.0),
 (10930, 1097.5),
 (10804, 1094.4),
 (10633, 1093.05),
 (10857, 1093.05),
 (10360, 1092.0),
 (10458, 1092.0),
 (10836, 1092.0),
 (10252, 1088.0),
 (10481, 1088.0),
 (10693, 1080.0),
 (10747, 1080.0),
 (10918, 1080.0),
 (10961, 1080.0),
 (11022, 1080.0),
 (11035, 1080.0),
 (11024, 1075.0),
 (10608, 1064.0),
 (10748, 1064.0),
 (10486, 1060.0),
 (10555, 1060.0),
 (10558, 1060.0),
 (10663, 1060.0),
 (10665, 1060.0),
 (10995, 1060.0),
 (11055, 1060.0),
 (10541, 1054.0),
 (10596, 1053.6),
 (10714, 1053.0),
 (10535, 1050.0),
 (10634, 1050.0),
 (10766, 1050.0),
 (10800, 1050.0),
 (10388, 1048.0),
 (10612, 1045.0),
 (10713, 1045.0),
 (10575, 1044.0),
 (10784, 1044.0),
 (10866, 1035.6),
 (11027, 1035.3),
 (10396, 1032.0),
 (10401, 1032.0),
 (10314, 1024.0),
 (10657, 1020.0),
 (10684, 1020.0),
 (10830, 1020.0),
 (10302, 1019.1999999999999),
 (10324, 1008.0),
 (10603, 1008.0),
 (10340, 1000.0),
 (10941, 1000.0),
 (10989, 1000.0),
 (10557, 997.5),
 (10836, 997.5),
 (10859, 997.5),
 (10834, 990.32),
 (10268, 990.0),
 (10994, 990.0),
 (10554, 986.0),
 (10718, 986.0),
 (10779, 986.0),
 (10816, 986.0),
 (10872, 986.0),
 (10314, 985.0),
 (10523, 975.0),
 (10721, 972.5),
 (10522, 960.0),
 (11002, 960.0),
 (10984, 959.75),
 (10283, 952.0),
 (10549, 950.0),
 (10641, 950.0),
 (10838, 950.0),
 (10991, 950.0),
 (10285, 943.1999999999999),
 (10677, 936.9),
 (10713, 936.9),
 (10265, 936.0),
 (10897, 932.04),
 (10368, 931.0),
 (10451, 931.0),
 (10681, 931.0),
 (10894, 930.0),
 (10949, 930.0),
 (10644, 920.0),
 (10814, 920.0),
 (10270, 919.9999999999999),
 (10572, 919.9999999999999),
 (10744, 919.9999999999999),
 (10418, 912.0),
 (10430, 912.0),
 (10464, 912.0),
 (10494, 912.0),
 (10499, 912.0),
 (10649, 912.0),
 (10733, 912.0),
 (10855, 912.0),
 (10976, 912.0),
 (11039, 912.0),
 (10658, 910.0),
 (10893, 906.15),
 (10530, 900.0),
 (10717, 900.0),
 (10729, 900.0),
 (10755, 900.0),
 (10808, 900.0),
 (11050, 900.0),
 (10312, 883.1999999999999),
 (10273, 882.0),
 (10423, 880.0),
 (10692, 878.0),
 (10977, 878.0),
 (10257, 877.5),
 (10773, 875.0),
 (10515, 872.5),
 (10680, 872.5),
 (10855, 872.5),
 (10297, 864.0),
 (10364, 864.0),
 (10424, 864.0),
 (10796, 864.0),
 (10373, 860.0),
 (10458, 860.0),
 (10814, 855.0),
 (10880, 855.0),
 (10933, 855.0),
 (10433, 851.1999999999999),
 (10774, 850.0),
 (10918, 850.0),
 (10362, 848.0),
 (10373, 848.0),
 (10965, 848.0),
 (10736, 842.0),
 (10327, 840.0),
 (10619, 840.0),
 (10635, 840.0),
 (10868, 840.0),
 (10889, 840.0),
 (10912, 840.0),
 (10990, 840.0),
 (11028, 840.0),
 (11056, 840.0),
 (10533, 835.1999999999999),
 (10556, 835.1999999999999),
 (10263, 834.0),
 (11053, 831.25),
 (10535, 825.0),
 (10803, 825.0),
 (10835, 825.0),
 (10514, 820.95),
 (10573, 819.9999999999999),
 (10650, 819.9999999999999),
 (11064, 819.9999999999999),
 (10442, 816.0),
 (10475, 816.0),
 (10583, 816.0),
 (10954, 816.0),
 (10895, 810.0),
 (11031, 810.0),
 (10829, 800.0),
 (10967, 800.0),
 (10978, 800.0),
 (10370, 798.0),
 (10436, 798.0),
 (10479, 798.0),
 (10757, 798.0),
 (10884, 798.0),
 (10634, 795.0),
 (10845, 795.0),
 (10999, 795.0),
 (10962, 792.0),
 (10389, 788.0),
 (10393, 781.2),
 (10260, 780.0),
 (10590, 780.0),
 (10696, 780.0),
 (10707, 780.0),
 (10727, 780.0),
 (10359, 778.4),
 (10551, 778.0),
 (10361, 777.6),
 (10372, 777.5999999999999),
 (10650, 776.7),
 (10751, 776.7),
 (10957, 776.7),
 (10657, 775.0),
 (10946, 775.0),
 (10607, 772.8),
 (10516, 772.0),
 (10342, 768.0),
 (10547, 768.0),
 (10397, 763.1999999999999),
 (10472, 763.1999999999999),
 (10258, 760.0),
 (10618, 760.0),
 (10690, 760.0),
 (10718, 760.0),
 (10766, 760.0),
 (10781, 760.0),
 (10790, 760.0),
 (10808, 760.0),
 (10979, 760.0),
 (10984, 760.0),
 (11018, 760.0),
 (11029, 760.0),
 (11046, 760.0),
 (10541, 757.8000000000001),
 (10938, 752.5),
 (10567, 750.0),
 (10670, 750.0),
 (10694, 750.0),
 (10719, 750.0),
 (10734, 750.0),
 (10880, 750.0),
 (10404, 747.0),
 (10421, 747.0),
 (10458, 747.0),
 (10487, 747.0),
 (10357, 744.0),
 (10664, 744.0),
 (11020, 744.0),
 (10624, 742.74),
 (10560, 739.5),
 (10627, 739.5),
 (10769, 739.5),
 (10309, 736.0),
 (10458, 736.0),
 (10748, 736.0),
 (11063, 736.0),
 (10267, 735.0),
 (10431, 735.0),
 (10566, 735.0),
 (10844, 735.0),
 (10479, 733.6),
 (10537, 730.8),
 (10277, 728.0),
 (10377, 728.0),
 (10327, 724.5),
 (10347, 720.0),
 (10471, 720.0),
 (10485, 720.0),
 (10522, 720.0),
 (10593, 720.0),
 (10640, 720.0),
 (10670, 720.0),
 (10756, 720.0),
 (10869, 720.0),
 (10902, 720.0),
 (10957, 720.0),
 (11070, 720.0),
 (10403, 714.0),
 (10829, 714.0),
 (11058, 714.0),
 (10504, 712.5),
 (10410, 704.0),
 (10573, 702.0),
 (10359, 700.0),
 (10551, 698.0),
 (10555, 697.5),
 (10675, 697.5),
 (10987, 696.0),
 (10330, 695.0),
 (10337, 695.0),
 (10497, 695.0),
 (10932, 690.1999999999999),
 (10507, 690.0),
 (10333, 688.0),
 (10549, 687.5),
 (11064, 687.5),
 (10440, 684.0),
 (10643, 684.0),
 (10714, 684.0),
 (10944, 684.0),
 (10440, 681.1),
 (10626, 680.0),
 (10653, 680.0),
 (10328, 672.0),
 (10492, 672.0),
 (10272, 667.2),
 (10390, 667.2),
 (10876, 665.0),
 (11031, 665.0),
 (11032, 665.0),
 (10278, 660.0),
 (10575, 660.0),
 (10679, 660.0),
 (10913, 660.0),
 (10825, 656.0),
 (10962, 656.0),
 (10796, 655.83),
 (10474, 655.1999999999999),
 (10427, 651.0),
 (10715, 651.0),
 (10729, 650.0),
 (10990, 650.0),
 (10661, 649.25),
 (10285, 648.0),
 (10552, 648.0),
 (10802, 647.25),
 (10646, 645.0),
 (10715, 645.0),
 (10901, 645.0),
 (11038, 645.0),
 (10848, 640.5),
 (11047, 640.5),
 (10253, 640.0),
 (10818, 640.0),
 (10975, 640.0),
 (11053, 640.0),
 (10580, 631.5),
 (10543, 630.0),
 (10630, 630.0),
 (10689, 630.0),
 (10701, 630.0),
 (10740, 630.0),
 (10845, 630.0),
 (10986, 630.0),
 (10985, 628.1999999999999),
 (10584, 625.0),
 (10722, 625.0),
 (10768, 625.0),
 (10853, 625.0),
 (10953, 625.0),
 (11018, 625.0),
 (10758, 624.6),
 (10868, 624.6),
 (10338, 624.0),
 (10564, 624.0),
 (10871, 624.0),
 (10411, 620.0),
 (10685, 620.0),
 (10924, 620.0),
 (10344, 616.0),
 (10298, 608.0),
 (10298, 608.0),
 (10301, 608.0),
 (10342, 608.0),
 (10346, 608.0),
 (10383, 608.0),
 (10469, 608.0),
 (10471, 608.0),
 (10896, 608.0),
 (10253, 604.8000000000001),
 (10475, 604.8000000000001),
 (10293, 600.0),
 (10309, 600.0),
 (10390, 600.0),
 (10399, 600.0),
 (10540, 600.0),
 (10564, 600.0),
 (10658, 600.0),
 (10659, 600.0),
 (10758, 600.0),
 (10833, 600.0),
 (10908, 600.0),
 (10929, 600.0),
 (10930, 600.0),
 (10982, 600.0),
 (11010, 600.0),
 (10565, 598.5),
 (10337, 597.5999999999999),
 (10273, 595.2),
 (10966, 591.5999999999999),
 (11044, 591.5999999999999),
 (10260, 591.0),
 (10298, 591.0),
 (10558, 590.4),
 (10285, 588.0),
 (10303, 588.0),
 (10447, 588.0),
 (10845, 588.0),
 (10890, 585.0),
 (10922, 585.0),
 (10931, 585.0),
 (10345, 584.0),
 (10396, 583.8000000000001),
 (10337, 582.4),
 (10693, 582.0),
 (10461, 579.6),
 (10356, 576.0),
 (10390, 576.0),
 (10419, 576.0),
 (10485, 576.0),
 (10451, 572.0),
 (10294, 571.1999999999999),
 (10455, 570.0),
 (10525, 570.0),
 (10527, 570.0),
 (10530, 570.0),
 (10536, 570.0),
 (10632, 570.0),
 (10642, 570.0),
 (10669, 570.0),
 (10714, 570.0),
 (10735, 570.0),
 (10749, 570.0),
 (10769, 570.0),
 (10784, 570.0),
 (10936, 570.0),
 (11041, 570.0),
 (10722, 562.5),
 (10849, 562.14),
 (10379, 561.6),
 (10342, 560.0),
 (10360, 560.0),
 (10362, 560.0),
 (10463, 560.0),
 (10573, 560.0),
 (10680, 560.0),
 (10939, 560.0),
 (10942, 560.0),
 (10996, 560.0),
 (10646, 558.0),
 (10688, 558.0),
 (10713, 558.0),
 (10932, 556.8),
 (10269, 556.0),
 (10287, 556.0),
 (10297, 556.0),
 (10294, 552.0),
 (10468, 552.0),
 (10663, 552.0),
 (10811, 552.0),
 (10636, 550.0),
 (10726, 550.0),
 (10727, 550.0),
 (10941, 550.0),
 (11000, 550.0),
 (11005, 550.0),
 (10369, 547.1999999999999),
 (10452, 546.0),
 (11039, 546.0),
 (10656, 544.6),
 (10284, 544.0),
 (10382, 544.0),
 (10385, 544.0),
 (10464, 544.0),
 (10546, 540.0),
 (10569, 540.0),
 (10595, 540.0),
 (10623, 540.0),
 (10657, 540.0),
 (10691, 540.0),
 (10868, 540.0),
 (10977, 540.0),
 (10979, 540.0),
 (10914, 537.5),
 (10264, 532.0),
 (10616, 532.0),
 (10740, 532.0),
 (10800, 530.0),
 (10977, 530.0),
 (11011, 530.0),
 (11026, 530.0),
 (10387, 528.0),
 (10480, 528.0),
 (10828, 527.0),
 (11029, 526.8),
 (10284, 526.5),
 (10627, 525.0),
 (10703, 525.0),
 (10780, 525.0),
 (10862, 525.0),
 (11001, 525.0),
 (11048, 525.0),
 (10312, 524.0),
 (10380, 524.0),
 (10554, 523.5),
 (10605, 523.5),
 (10653, 523.5),
 (10877, 523.5),
 (10932, 523.5),
 (11070, 523.5),
 (10649, 522.0),
 (10839, 522.0),
 (10429, 520.0),
 (10886, 520.0),
 (10946, 520.0),
 (10350, 518.4),
 (10522, 517.8),
 (10560, 517.8),
 (10834, 517.8),
 (10320, 516.0),
 (10399, 516.0),
 (10455, 516.0),
 (10611, 510.0),
 (10728, 510.0),
 (10768, 510.0),
 (11061, 510.0),
 (10319, 509.59999999999997),
 (10303, 504.0),
 (10399, 504.0),
 (10400, 504.0),
 (10407, 504.0),
 (10442, 504.0),
 (10553, 504.0),
 (10707, 504.0),
 (10830, 504.0),
 (10983, 504.0),
 (10499, 500.0),
 (10603, 500.0),
 (10639, 500.0),
 (10700, 500.0),
 (10766, 500.0),
 (10934, 500.0),
 (10985, 500.0),
 (11026, 500.0),
 (11076, 500.0),
 (10668, 498.75),
 (10872, 498.75),
 (10450, 496.0),
 (10478, 496.0),
 (10519, 496.0),
 (10724, 496.0),
 (10841, 496.0),
 (10895, 495.0),
 (10562, 493.0),
 (10574, 493.0),
 (10599, 493.0),
 (10606, 493.0),
 (10671, 493.0),
 (10563, 490.0),
 (10761, 490.0),
 (10849, 490.0),
 (11066, 490.0),
 (10954, 488.59999999999997),
 (10623, 488.25),
 (10255, 486.5),
 (10469, 486.5),
 (10304, 480.0),
 (10400, 480.0),
 (10404, 480.0),
 (10606, 480.0),
 (11031, 480.0),
 (11046, 480.0),
 (10273, 475.2),
 (10563, 475.0),
 (10714, 475.0),
 (10925, 475.0),
 (10368, 473.2),
 (10277, 472.79999999999995),
 (10442, 472.0),
 (10451, 470.40000000000003),
 (10686, 468.45),
 (10723, 468.45),
 (10279, 468.0),
 (10294, 468.0),
 (10523, 468.0),
 (10836, 468.0),
 (10911, 468.0),
 (11059, 468.0),
 (10691, 466.79999999999995),
 (10827, 465.0),
 (11076, 465.0),
 (10846, 462.0),
 (10962, 462.0),
 (10923, 460.0),
 (10522, 459.99999999999994),
 (10788, 459.99999999999994),
 (10837, 459.99999999999994),
 (11012, 459.99999999999994),
 (10270, 456.0),
 (10439, 456.0),
 (10458, 456.0),
 (10624, 456.0),
 (10664, 456.0),
 (10966, 456.0),
 (11077, 456.0),
 (10646, 455.0),
 (11008, 451.5),
 (10382, 450.0),
 (10600, 450.0),
 (10628, 450.0),
 (10697, 450.0),
 (10845, 450.0),
 (10846, 450.0),
 (10850, 450.0),
 (10869, 450.0),
 (10885, 450.0),
 (11017, 450.0),
 (11047, 450.0),
 (11071, 450.0),
 (10404, 448.0),
 (10693, 447.0),
 (10746, 443.7),
 (10638, 442.05),
 (10872, 442.05),
 (10903, 442.05),
 (11024, 442.05),
 (10302, 441.59999999999997),
 (10659, 441.59999999999997),
 (10943, 441.0),
 (10304, 440.0),
 (10606, 440.0),
 (10706, 440.0),
 (10858, 439.0),
 (10974, 439.0),
 (10540, 437.5),
 (10569, 437.5),
 (10826, 437.5),
 (10886, 437.5),
 (10443, 436.79999999999995),
 (10296, 432.0),
 (10305, 432.0),
 (10319, 432.0),
 (10390, 432.0),
 (10398, 432.0),
 (10402, 432.0),
 (10407, 432.0),
 (10559, 432.0),
 (11039, 432.0),
 (10626, 430.0),
 (10701, 430.0),
 (11011, 430.0),
 (10513, 427.5),
 (10906, 427.5),
 (10958, 427.0),
 (10497, 425.59999999999997),
 (10956, 424.0),
 (10326, 422.40000000000003),
 (10503, 421.0),
 (10376, 420.0),
 (10498, 420.0),
 (10502, 420.0),
 (10619, 420.0),
 (10651, 420.0),
 (10663, 420.0),
 (10707, 420.0),
 (10757, 420.0),
 (10758, 420.0),
 (10797, 420.0),
 (10813, 420.0),
 (10823, 420.0),
 (11035, 420.0),
 (11063, 420.0),
 (10919, 418.79999999999995),
 (10418, 418.0),
 (10607, 417.59999999999997),
 (10296, 417.0),
 (10831, 414.0),
 (10982, 414.0),
 (10576, 408.45),
 (10676, 408.45),
 (10300, 408.0),
 (10384, 408.0),
 (10512, 408.0),
 (10532, 408.0),
 (10637, 406.25),
 (10711, 405.3),
 (10828, 405.0),
 (10927, 405.0),
 (10365, 403.20000000000005),
 (10254, 403.2),
 (10367, 403.2),
 (10272, 400.0),
 (10382, 400.0),
 (10405, 400.0),
 (10430, 400.0),
 (10511, 400.0),
 (10513, 400.0),
 (10695, 400.0),
 (10731, 400.0),
 (10763, 400.0),
 (10861, 400.0),
 (10882, 400.0),
 (10884, 400.0),
 (10952, 400.0),
 (10978, 400.0),
 (10610, 399.0),
 (10866, 399.0),
 (10357, 398.4),
 (10594, 397.5),
 (10675, 397.5),
 (10697, 397.5),
 (10839, 397.5),
 (10930, 397.5),
 (10389, 396.8),
 (10328, 396.0),
 (10341, 396.0),
 (10354, 396.0),
 (10411, 396.0),
 (10748, 396.0),
 (10747, 395.09999999999997),
 (10307, 394.0),
 (10394, 394.0),
 (10626, 393.59999999999997),
 (10256, 393.0),
 (10421, 393.0),
 (10437, 393.0),
 (10483, 392.0),
 (10571, 392.0),
 (10746, 392.0),
 (10355, 390.0),
 (10368, 390.0),
 (10597, 390.0),
 (10690, 390.0),
 (10854, 390.0),
 (10915, 390.0),
 (10916, 390.0),
 ...]

In [34]:
import pandas as pd

In [41]:
# Query 3: numero de pedidos por dia en un dataframe
mydb = mysql.connector.connect(
user='root', 
password='AlumnaAdalab',
host='127.0.0.1',
database='northwind')

cursor = mydb.cursor()

query3 = "SELECT order_id, order_date, COUNT(order_id) FROM orders GROUP BY order_id, order_date" 

cursor.execute(query3)

resultado3 = cursor.fetchall()

df = pd.DataFrame(resultado3, columns = ['Order ID', 'Order Date', 'No. of Orders'])

df.head(20)

    Order ID Order Date  No. of Orders
0      10248 1996-07-04              1
1      10249 1996-07-05              1
2      10250 1996-07-08              1
3      10251 1996-07-08              1
4      10252 1996-07-09              1
5      10253 1996-07-10              1
6      10254 1996-07-11              1
7      10255 1996-07-12              1
8      10256 1996-07-15              1
9      10257 1996-07-16              1
10     10258 1996-07-17              1
11     10259 1996-07-18              1
12     10260 1996-07-19              1
13     10261 1996-07-19              1
14     10262 1996-07-22              1
15     10263 1996-07-23              1
16     10264 1996-07-24              1
17     10265 1996-07-25              1
18     10266 1996-07-26              1
19     10267 1996-07-29              1

In [43]:
# Query 4: pedidos hechos por Nancy Davolio

mydb = mysql.connector.connect(
user='root', 
password='AlumnaAdalab',
host='127.0.0.1',
database='northwind')

cursor = mydb.cursor()

query4 = 'SELECT * FROM orders WHERE employee_id IN (SELECT employee_id FROM employees WHERE first_name = "Nancy" AND last_name = "Davolio")'

cursor.execute(query4)

resultado4 = cursor.fetchall()
print(resultado4)

cursor.close()
mydb.close()

[(10258, 'ERNSH', 1, datetime.datetime(1996, 7, 17, 0, 0), datetime.datetime(1996, 8, 14, 0, 0), datetime.datetime(1996, 7, 23, 0, 0), 1, 140.51, 'Ernst Handel', 'Kirchgasse 6', 'Graz', '', '8010', 'Austria'), (10270, 'WARTH', 1, datetime.datetime(1996, 8, 1, 0, 0), datetime.datetime(1996, 8, 29, 0, 0), datetime.datetime(1996, 8, 2, 0, 0), 1, 136.54, 'Wartian Herkku', 'Torikatu 38', 'Oulu', '', '90110', 'Finland'), (10275, 'MAGAA', 1, datetime.datetime(1996, 8, 7, 0, 0), datetime.datetime(1996, 9, 4, 0, 0), datetime.datetime(1996, 8, 9, 0, 0), 1, 26.93, 'Magazzini Alimentari Riuniti', 'Via Ludovico il Moro 22', 'Bergamo', '', '24100', 'Italy'), (10285, 'QUICK', 1, datetime.datetime(1996, 8, 20, 0, 0), datetime.datetime(1996, 9, 17, 0, 0), datetime.datetime(1996, 8, 26, 0, 0), 2, 76.83, 'QUICK-Stop', 'Taucherstra�e 10', 'Cunewalde', '', '1307', 'Germany'), (10292, 'TRADH', 1, datetime.datetime(1996, 8, 28, 0, 0), datetime.datetime(1996, 9, 25, 0, 0), datetime.datetime(1996, 9, 2, 0, 0), 2, 1.35, 'Tradi�ao Hipermercados', 'Av. In�s de Castro, 414', 'Sao Paulo', 'SP', '05634-030', 'Brazil'), (10293, 'TORTU', 1, datetime.datetime(1996, 8, 29, 0, 0), datetime.datetime(1996, 9, 26, 0, 0), datetime.datetime(1996, 9, 11, 0, 0), 3, 21.18, 'Tortuga Restaurante', 'Avda. Azteca 123', 'M�xico D.F.', '', '5033', 'Mexico'), (10304, 'TORTU', 1, datetime.datetime(1996, 9, 12, 0, 0), datetime.datetime(1996, 10, 10, 0, 0), datetime.datetime(1996, 9, 17, 0, 0), 2, 63.79, 'Tortuga Restaurante', 'Avda. Azteca 123', 'M�xico D.F.', '', '5033', 'Mexico'), (10306, 'ROMEY', 1, datetime.datetime(1996, 9, 16, 0, 0), datetime.datetime(1996, 10, 14, 0, 0), datetime.datetime(1996, 9, 23, 0, 0), 3, 7.56, 'Romero y tomillo', 'Gran V�a, 1', 'Madrid', '', '28001', 'Spain'), (10311, 'DUMON', 1, datetime.datetime(1996, 9, 20, 0, 0), datetime.datetime(1996, 10, 4, 0, 0), datetime.datetime(1996, 9, 26, 0, 0), 3, 24.69, 'Du monde entier', '67, rue des Cinquante Otages', 'Nantes', '', '44000', 'France'), (10314, 'RATTC', 1, datetime.datetime(1996, 9, 25, 0, 0), datetime.datetime(1996, 10, 23, 0, 0), datetime.datetime(1996, 10, 4, 0, 0), 2, 74.16, 'Rattlesnake Canyon Grocery', '2817 Milton Dr.', 'Albuquerque', 'NM', '87110', 'USA'), (10316, 'RATTC', 1, datetime.datetime(1996, 9, 27, 0, 0), datetime.datetime(1996, 10, 25, 0, 0), datetime.datetime(1996, 10, 8, 0, 0), 3, 150.15, 'Rattlesnake Canyon Grocery', '2817 Milton Dr.', 'Albuquerque', 'NM', '87110', 'USA'), (10325, 'KOENE', 1, datetime.datetime(1996, 10, 9, 0, 0), datetime.datetime(1996, 10, 23, 0, 0), datetime.datetime(1996, 10, 14, 0, 0), 3, 64.86, 'K�niglich Essen', 'Maubelstr. 90', 'Brandenburg', '', '14776', 'Germany'), (10340, 'BONAP', 1, datetime.datetime(1996, 10, 29, 0, 0), datetime.datetime(1996, 11, 26, 0, 0), datetime.datetime(1996, 11, 8, 0, 0), 3, 166.31, "Bon app'", '12, rue des Bouchers', 'Marseille', '', '13008', 'France'), (10351, 'ERNSH', 1, datetime.datetime(1996, 11, 11, 0, 0), datetime.datetime(1996, 12, 9, 0, 0), datetime.datetime(1996, 11, 20, 0, 0), 1, 162.33, 'Ernst Handel', 'Kirchgasse 6', 'Graz', '', '8010', 'Austria'), (10357, 'LILAS', 1, datetime.datetime(1996, 11, 19, 0, 0), datetime.datetime(1996, 12, 17, 0, 0), datetime.datetime(1996, 12, 2, 0, 0), 3, 34.88, 'LILA-Supermercado', 'Carrera 52 con Ave. Bol�var #65-98 Llano Largo', 'Barquisimeto', 'Lara', '3508', 'Venezuela'), (10361, 'QUICK', 1, datetime.datetime(1996, 11, 22, 0, 0), datetime.datetime(1996, 12, 20, 0, 0), datetime.datetime(1996, 12, 3, 0, 0), 2, 183.17, 'QUICK-Stop', 'Taucherstra�e 10', 'Cunewalde', '', '1307', 'Germany'), (10364, 'EASTC', 1, datetime.datetime(1996, 11, 26, 0, 0), datetime.datetime(1997, 1, 7, 0, 0), datetime.datetime(1996, 12, 4, 0, 0), 1, 71.97, 'Eastern Connection', '35 King George', 'London', '', 'WX3 6FW', 'UK'), (10371, 'LAMAI', 1, datetime.datetime(1996, 12, 3, 0, 0), datetime.datetime(1996, 12, 31, 0, 0), datetime.datetime(1996, 12, 24, 0, 0), 1, 0.45, "La maison d'Asie", '1 rue Alsace-Lorraine', 'Toulouse', '', '31000', 'France'), (10374, 'WOLZA', 1, datetime.datetime(1996, 12, 5, 0, 0), datetime.datetime(1997, 1, 2, 0, 0), datetime.datetime(1996, 12, 9, 0, 0), 3, 3.94, 'Wolski Zajazd', 'ul. Filtrowa 68', 'Warszawa', '', '01-012', 'Poland'), (10376, 'MEREP', 1, datetime.datetime(1996, 12, 9, 0, 0), datetime.datetime(1997, 1, 6, 0, 0), datetime.datetime(1996, 12, 13, 0, 0), 2, 20.39, 'M�re Paillarde', '43 rue St. Laurent', 'Montr�al', 'Qu�bec', 'H1J 1C3', 'Canada'), (10377, 'SEVES', 1, datetime.datetime(1996, 12, 9, 0, 0), datetime.datetime(1997, 1, 6, 0, 0), datetime.datetime(1996, 12, 13, 0, 0), 3, 22.21, 'Seven Seas Imports', '90 Wadhurst Rd.', 'London', '', 'OX15 4NB', 'UK'), (10385, 'SPLIR', 1, datetime.datetime(1996, 12, 17, 0, 0), datetime.datetime(1997, 1, 14, 0, 0), datetime.datetime(1996, 12, 23, 0, 0), 2, 30.96, 'Split Rail Beer & Ale', 'P.O. Box 555', 'Lander', 'WY', '82520', 'USA'), (10387, 'SANTG', 1, datetime.datetime(1996, 12, 18, 0, 0), datetime.datetime(1997, 1, 15, 0, 0), datetime.datetime(1996, 12, 20, 0, 0), 2, 93.63, 'Sant� Gourmet', 'Erling Skakkes gate 78', 'Stavern', '', '4110', 'Norway'), (10393, 'SAVEA', 1, datetime.datetime(1996, 12, 25, 0, 0), datetime.datetime(1997, 1, 22, 0, 0), datetime.datetime(1997, 1, 3, 0, 0), 3, 126.56, 'Save-a-lot Markets', '187 Suffolk Ln.', 'Boise', 'ID', '83720', 'USA'), (10394, 'HUNGC', 1, datetime.datetime(1996, 12, 25, 0, 0), datetime.datetime(1997, 1, 22, 0, 0), datetime.datetime(1997, 1, 3, 0, 0), 3, 30.34, 'Hungry Coyote Import Store', 'City Center Plaza 516 Main St.', 'Elgin', 'OR', '97827', 'USA'), (10396, 'FRANK', 1, datetime.datetime(1996, 12, 27, 0, 0), datetime.datetime(1997, 1, 10, 0, 0), datetime.datetime(1997, 1, 6, 0, 0), 3, 135.35, 'Frankenversand', 'Berliner Platz 43', 'M�nchen', '', '80805', 'Germany'), (10400, 'EASTC', 1, datetime.datetime(1997, 1, 1, 0, 0), datetime.datetime(1997, 1, 29, 0, 0), datetime.datetime(1997, 1, 16, 0, 0), 3, 83.93, 'Eastern Connection', '35 King George', 'London', '', 'WX3 6FW', 'UK'), (10401, 'RATTC', 1, datetime.datetime(1997, 1, 1, 0, 0), datetime.datetime(1997, 1, 29, 0, 0), datetime.datetime(1997, 1, 10, 0, 0), 1, 12.51, 'Rattlesnake Canyon Grocery', '2817 Milton Dr.', 'Albuquerque', 'NM', '87110', 'USA'), (10405, 'LINOD', 1, datetime.datetime(1997, 1, 6, 0, 0), datetime.datetime(1997, 2, 3, 0, 0), datetime.datetime(1997, 1, 22, 0, 0), 1, 34.82, 'LINO-Delicateses', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', 'Nueva Esparta', '4980', 'Venezuela'), (10453, 'AROUT', 1, datetime.datetime(1997, 2, 21, 0, 0), datetime.datetime(1997, 3, 21, 0, 0), datetime.datetime(1997, 2, 26, 0, 0), 2, 25.36, 'Around the Horn', 'Brook Farm Stratford St. Mary', 'Colchester', 'Essex', 'CO7 6JX', 'UK'), (10461, 'LILAS', 1, datetime.datetime(1997, 2, 28, 0, 0), datetime.datetime(1997, 3, 28, 0, 0), datetime.datetime(1997, 3, 5, 0, 0), 3, 148.61, 'LILA-Supermercado', 'Carrera 52 con Ave. Bol�var #65-98 Llano Largo', 'Barquisimeto', 'Lara', '3508', 'Venezuela'), (10465, 'VAFFE', 1, datetime.datetime(1997, 3, 5, 0, 0), datetime.datetime(1997, 4, 2, 0, 0), datetime.datetime(1997, 3, 14, 0, 0), 3, 145.04, 'Vaffeljernet', 'Smagsloget 45', '�rhus', '', '8200', 'Denmark'), (10469, 'WHITC', 1, datetime.datetime(1997, 3, 10, 0, 0), datetime.datetime(1997, 4, 7, 0, 0), datetime.datetime(1997, 3, 14, 0, 0), 1, 60.18, 'White Clover Markets', '1029 - 12th Ave. S.', 'Seattle', 'WA', '98124', 'USA'), (10473, 'ISLAT', 1, datetime.datetime(1997, 3, 13, 0, 0), datetime.datetime(1997, 3, 27, 0, 0), datetime.datetime(1997, 3, 21, 0, 0), 3, 16.37, 'Island Trading', 'Garden House Crowther Way', 'Cowes', 'Isle of Wight', 'PO31 7PJ', 'UK'), (10482, 'LAZYK', 1, datetime.datetime(1997, 3, 21, 0, 0), datetime.datetime(1997, 4, 18, 0, 0), datetime.datetime(1997, 4, 10, 0, 0), 3, 7.48, 'Lazy K Kountry Store', '12 Orchestra Terrace', 'Walla Walla', 'WA', '99362', 'USA'), (10486, 'HILAA', 1, datetime.datetime(1997, 3, 26, 0, 0), datetime.datetime(1997, 4, 23, 0, 0), datetime.datetime(1997, 4, 2, 0, 0), 2, 30.53, 'HILARION-Abastos', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Crist�bal', 'T�chira', '5022', 'Venezuela'), (10508, 'OTTIK', 1, datetime.datetime(1997, 4, 16, 0, 0), datetime.datetime(1997, 5, 14, 0, 0), datetime.datetime(1997, 5, 13, 0, 0), 2, 4.99, 'Ottilies K�seladen', 'Mehrheimerstr. 369', 'K�ln', '', '50739', 'Germany'), (10524, 'BERGS', 1, datetime.datetime(1997, 5, 1, 0, 0), datetime.datetime(1997, 5, 29, 0, 0), datetime.datetime(1997, 5, 7, 0, 0), 2, 244.79, 'Berglunds snabbk�p', 'Berguvsv�gen  8', 'Lule�', '', 'S-958 22', 'Sweden'), (10525, 'BONAP', 1, datetime.datetime(1997, 5, 2, 0, 0), datetime.datetime(1997, 5, 30, 0, 0), datetime.datetime(1997, 5, 23, 0, 0), 2, 11.06, "Bon app'", '12, rue des Bouchers', 'Marseille', '', '13008', 'France'), (10537, 'RICSU', 1, datetime.datetime(1997, 5, 14, 0, 0), datetime.datetime(1997, 5, 28, 0, 0), datetime.datetime(1997, 5, 19, 0, 0), 1, 78.85, 'Richter Supermarkt', 'Starenweg 5', 'Gen�ve', '', '1204', 'Switzerland'), (10542, 'KOENE', 1, datetime.datetime(1997, 5, 20, 0, 0), datetime.datetime(1997, 6, 17, 0, 0), datetime.datetime(1997, 5, 26, 0, 0), 3, 10.95, 'K�niglich Essen', 'Maubelstr. 90', 'Brandenburg', '', '14776', 'Germany'), (10546, 'VICTE', 1, datetime.datetime(1997, 5, 23, 0, 0), datetime.datetime(1997, 6, 20, 0, 0), datetime.datetime(1997, 5, 27, 0, 0), 3, 194.72, 'Victuailles en stock', '2, rue du Commerce', 'Lyon', '', '69004', 'France'), (10558, 'AROUT', 1, datetime.datetime(1997, 6, 4, 0, 0), datetime.datetime(1997, 7, 2, 0, 0), datetime.datetime(1997, 6, 10, 0, 0), 2, 72.97, 'Around the Horn', 'Brook Farm Stratford St. Mary', 'Colchester', 'Essex', 'CO7 6JX', 'UK'), (10562, 'REGGC', 1, datetime.datetime(1997, 6, 9, 0, 0), datetime.datetime(1997, 7, 7, 0, 0), datetime.datetime(1997, 6, 12, 0, 0), 1, 22.95, 'Reggiani Caseifici', 'Strada Provinciale 124', 'Reggio Emilia', '', '42100', 'Italy'), (10567, 'HUNGO', 1, datetime.datetime(1997, 6, 12, 0, 0), datetime.datetime(1997, 7, 10, 0, 0), datetime.datetime(1997, 6, 17, 0, 0), 1, 33.97, 'Hungry Owl All-Night Grocers', '8 Johnstown Road', 'Cork', 'Co. Cork', '', 'Ireland'), (10579, 'LETSS', 1, datetime.datetime(1997, 6, 25, 0, 0), datetime.datetime(1997, 7, 23, 0, 0), datetime.datetime(1997, 7, 4, 0, 0), 2, 13.73, "Let's Stop N Shop", '87 Polk St. Suite 5', 'San Francisco', 'CA', '94117', 'USA'), (10587, 'QUEDE', 1, datetime.datetime(1997, 7, 2, 0, 0), datetime.datetime(1997, 7, 30, 0, 0), datetime.datetime(1997, 7, 9, 0, 0), 1, 62.52, 'Que Del�cia', 'Rua da Panificadora, 12', 'Rio de Janeiro', 'RJ', '02389-673', 'Brazil'), (10591, 'VAFFE', 1, datetime.datetime(1997, 7, 7, 0, 0), datetime.datetime(1997, 7, 21, 0, 0), datetime.datetime(1997, 7, 16, 0, 0), 1, 55.92, 'Vaffeljernet', 'Smagsloget 45', '�rhus', '', '8200', 'Denmark'), (10598, 'RATTC', 1, datetime.datetime(1997, 7, 14, 0, 0), datetime.datetime(1997, 8, 11, 0, 0), datetime.datetime(1997, 7, 18, 0, 0), 3, 44.42, 'Rattlesnake Canyon Grocery', '2817 Milton Dr.', 'Albuquerque', 'NM', '87110', 'USA'), (10604, 'FURIB', 1, datetime.datetime(1997, 7, 18, 0, 0), datetime.datetime(1997, 8, 15, 0, 0), datetime.datetime(1997, 7, 29, 0, 0), 1, 7.46, 'Furia Bacalhau e Frutos do Mar', 'Jardim das rosas n. 32', 'Lisboa', '', '1675', 'Portugal'), (10605, 'MEREP', 1, datetime.datetime(1997, 7, 21, 0, 0), datetime.datetime(1997, 8, 18, 0, 0), datetime.datetime(1997, 7, 29, 0, 0), 2, 379.13, 'M�re Paillarde', '43 rue St. Laurent', 'Montr�al', 'Qu�bec', 'H1J 1C3', 'Canada'), (10612, 'SAVEA', 1, datetime.datetime(1997, 7, 28, 0, 0), datetime.datetime(1997, 8, 25, 0, 0), datetime.datetime(1997, 8, 1, 0, 0), 2, 544.08, 'Save-a-lot Markets', '187 Suffolk Ln.', 'Boise', 'ID', '83720', 'USA'), (10616, 'GREAL', 1, datetime.datetime(1997, 7, 31, 0, 0), datetime.datetime(1997, 8, 28, 0, 0), datetime.datetime(1997, 8, 5, 0, 0), 2, 116.53, 'Great Lakes Food Market', '2732 Baker Blvd.', 'Eugene', 'OR', '97403', 'USA'), (10618, 'MEREP', 1, datetime.datetime(1997, 8, 1, 0, 0), datetime.datetime(1997, 9, 12, 0, 0), datetime.datetime(1997, 8, 8, 0, 0), 1, 154.68, 'M�re Paillarde', '43 rue St. Laurent', 'Montr�al', 'Qu�bec', 'H1J 1C3', 'Canada'), (10626, 'BERGS', 1, datetime.datetime(1997, 8, 11, 0, 0), datetime.datetime(1997, 9, 8, 0, 0), datetime.datetime(1997, 8, 20, 0, 0), 2, 138.69, 'Berglunds snabbk�p', 'Berguvsv�gen  8', 'Lule�', '', 'S-958 22', 'Sweden'), (10630, 'KOENE', 1, datetime.datetime(1997, 8, 13, 0, 0), datetime.datetime(1997, 9, 10, 0, 0), datetime.datetime(1997, 8, 19, 0, 0), 2, 32.35, 'K�niglich Essen', 'Maubelstr. 90', 'Brandenburg', '', '14776', 'Germany'), (10653, 'FRANK', 1, datetime.datetime(1997, 9, 2, 0, 0), datetime.datetime(1997, 9, 30, 0, 0), datetime.datetime(1997, 9, 19, 0, 0), 1, 93.25, 'Frankenversand', 'Berliner Platz 43', 'M�nchen', '', '80805', 'Germany'), (10655, 'REGGC', 1, datetime.datetime(1997, 9, 3, 0, 0), datetime.datetime(1997, 10, 1, 0, 0), datetime.datetime(1997, 9, 11, 0, 0), 2, 4.41, 'Reggiani Caseifici', 'Strada Provinciale 124', 'Reggio Emilia', '', '42100', 'Italy'), (10664, 'FURIB', 1, datetime.datetime(1997, 9, 10, 0, 0), datetime.datetime(1997, 10, 8, 0, 0), datetime.datetime(1997, 9, 19, 0, 0), 3, 1.27, 'Furia Bacalhau e Frutos do Mar', 'Jardim das rosas n. 32', 'Lisboa', '', '1675', 'Portugal'), (10665, 'LONEP', 1, datetime.datetime(1997, 9, 11, 0, 0), datetime.datetime(1997, 10, 9, 0, 0), datetime.datetime(1997, 9, 17, 0, 0), 2, 26.31, 'Lonesome Pine Restaurant', '89 Chiaroscuro Rd.', 'Portland', 'OR', '97219', 'USA'), (10668, 'WANDK', 1, datetime.datetime(1997, 9, 15, 0, 0), datetime.datetime(1997, 10, 13, 0, 0), datetime.datetime(1997, 9, 23, 0, 0), 2, 47.22, 'Die Wandernde Kuh', 'Adenauerallee 900', 'Stuttgart', '', '70563', 'Germany'), (10671, 'FRANR', 1, datetime.datetime(1997, 9, 17, 0, 0), datetime.datetime(1997, 10, 15, 0, 0), datetime.datetime(1997, 9, 24, 0, 0), 1, 30.34, 'France restauration', '54, rue Royale', 'Nantes', '', '44000', 'France'), (10677, 'ANTON', 1, datetime.datetime(1997, 9, 22, 0, 0), datetime.datetime(1997, 10, 20, 0, 0), datetime.datetime(1997, 9, 26, 0, 0), 3, 4.03, 'Antonio Moreno Taquer�a', 'Mataderos  2312', 'M�xico D.F.', '', '5023', 'Mexico'), (10680, 'OLDWO', 1, datetime.datetime(1997, 9, 24, 0, 0), datetime.datetime(1997, 10, 22, 0, 0), datetime.datetime(1997, 9, 26, 0, 0), 1, 26.61, 'Old World Delicatessen', '2743 Bering St.', 'Anchorage', 'AK', '99508', 'USA'), (10689, 'BERGS', 1, datetime.datetime(1997, 10, 1, 0, 0), datetime.datetime(1997, 10, 29, 0, 0), datetime.datetime(1997, 10, 7, 0, 0), 2, 13.42, 'Berglunds snabbk�p', 'Berguvsv�gen  8', 'Lule�', '', 'S-958 22', 'Sweden'), (10690, 'HANAR', 1, datetime.datetime(1997, 10, 2, 0, 0), datetime.datetime(1997, 10, 30, 0, 0), datetime.datetime(1997, 10, 3, 0, 0), 1, 15.8, 'Hanari Carnes', 'Rua do Pa�o, 67', 'Rio de Janeiro', 'RJ', '05454-876', 'Brazil'), (10709, 'GOURL', 1, datetime.datetime(1997, 10, 17, 0, 0), datetime.datetime(1997, 11, 14, 0, 0), datetime.datetime(1997, 11, 20, 0, 0), 3, 210.8, 'Gourmet Lanchonetes', 'Av. Brasil, 442', 'Campinas', 'SP', '04876-786', 'Brazil'), (10710, 'FRANS', 1, datetime.datetime(1997, 10, 20, 0, 0), datetime.datetime(1997, 11, 17, 0, 0), datetime.datetime(1997, 10, 23, 0, 0), 1, 4.98, 'Franchi S.p.A.', 'Via Monte Bianco 34', 'Torino', '', '10100', 'Italy'), (10713, 'SAVEA', 1, datetime.datetime(1997, 10, 22, 0, 0), datetime.datetime(1997, 11, 19, 0, 0), datetime.datetime(1997, 10, 24, 0, 0), 1, 167.05, 'Save-a-lot Markets', '187 Suffolk Ln.', 'Boise', 'ID', '83720', 'USA'), (10717, 'FRANK', 1, datetime.datetime(1997, 10, 24, 0, 0), datetime.datetime(1997, 11, 21, 0, 0), datetime.datetime(1997, 10, 29, 0, 0), 2, 59.25, 'Frankenversand', 'Berliner Platz 43', 'M�nchen', '', '80805', 'Germany'), (10718, 'KOENE', 1, datetime.datetime(1997, 10, 27, 0, 0), datetime.datetime(1997, 11, 24, 0, 0), datetime.datetime(1997, 10, 29, 0, 0), 3, 170.88, 'K�niglich Essen', 'Maubelstr. 90', 'Brandenburg', '', '14776', 'Germany'), (10733, 'BERGS', 1, datetime.datetime(1997, 11, 7, 0, 0), datetime.datetime(1997, 12, 5, 0, 0), datetime.datetime(1997, 11, 10, 0, 0), 3, 110.11, 'Berglunds snabbk�p', 'Berguvsv�gen  8', 'Lule�', '', 'S-958 22', 'Sweden'), (10743, 'AROUT', 1, datetime.datetime(1997, 11, 17, 0, 0), datetime.datetime(1997, 12, 15, 0, 0), datetime.datetime(1997, 11, 21, 0, 0), 2, 23.72, 'Around the Horn', 'Brook Farm Stratford St. Mary', 'Colchester', 'Essex', 'CO7 6JX', 'UK'), (10746, 'CHOPS', 1, datetime.datetime(1997, 11, 19, 0, 0), datetime.datetime(1997, 12, 17, 0, 0), datetime.datetime(1997, 11, 21, 0, 0), 3, 31.43, 'Chop-suey Chinese', 'Hauptstr. 31', 'Bern', '', '3012', 'Switzerland'), (10773, 'ERNSH', 1, datetime.datetime(1997, 12, 11, 0, 0), datetime.datetime(1998, 1, 8, 0, 0), datetime.datetime(1997, 12, 16, 0, 0), 3, 96.43, 'Ernst Handel', 'Kirchgasse 6', 'Graz', '', '8010', 'Austria'), (10776, 'ERNSH', 1, datetime.datetime(1997, 12, 15, 0, 0), datetime.datetime(1998, 1, 12, 0, 0), datetime.datetime(1997, 12, 18, 0, 0), 3, 351.53, 'Ernst Handel', 'Kirchgasse 6', 'Graz', '', '8010', 'Austria'), (10785, 'GROSR', 1, datetime.datetime(1997, 12, 18, 0, 0), datetime.datetime(1998, 1, 15, 0, 0), datetime.datetime(1997, 12, 24, 0, 0), 3, 1.51, 'GROSELLA-Restaurante', '5� Ave. Los Palos Grandes', 'Caracas', 'DF', '1081', 'Venezuela'), (10788, 'QUICK', 1, datetime.datetime(1997, 12, 22, 0, 0), datetime.datetime(1998, 1, 19, 0, 0), datetime.datetime(1998, 1, 19, 0, 0), 2, 42.7, 'QUICK-Stop', 'Taucherstra�e 10', 'Cunewalde', '', '1307', 'Germany'), (10789, 'FOLIG', 1, datetime.datetime(1997, 12, 22, 0, 0), datetime.datetime(1998, 1, 19, 0, 0), datetime.datetime(1997, 12, 31, 0, 0), 2, 100.6, 'Folies gourmandes', '184, chauss�e de Tournai', 'Lille', '', '59000', 'France'), (10792, 'WOLZA', 1, datetime.datetime(1997, 12, 23, 0, 0), datetime.datetime(1998, 1, 20, 0, 0), datetime.datetime(1997, 12, 31, 0, 0), 3, 23.79, 'Wolski Zajazd', 'ul. Filtrowa 68', 'Warszawa', '', '01-012', 'Poland'), (10800, 'SEVES', 1, datetime.datetime(1997, 12, 26, 0, 0), datetime.datetime(1998, 1, 23, 0, 0), datetime.datetime(1998, 1, 5, 0, 0), 3, 137.44, 'Seven Seas Imports', '90 Wadhurst Rd.', 'London', '', 'OX15 4NB', 'UK'), (10813, 'RICAR', 1, datetime.datetime(1998, 1, 5, 0, 0), datetime.datetime(1998, 2, 2, 0, 0), datetime.datetime(1998, 1, 9, 0, 0), 1, 47.38, 'Ricardo Adocicados', 'Av. Copacabana, 267', 'Rio de Janeiro', 'RJ', '02389-890', 'Brazil'), (10821, 'SPLIR', 1, datetime.datetime(1998, 1, 8, 0, 0), datetime.datetime(1998, 2, 5, 0, 0), datetime.datetime(1998, 1, 15, 0, 0), 1, 36.68, 'Split Rail Beer & Ale', 'P.O. Box 555', 'Lander', 'WY', '82520', 'USA'), (10825, 'DRACD', 1, datetime.datetime(1998, 1, 9, 0, 0), datetime.datetime(1998, 2, 6, 0, 0), datetime.datetime(1998, 1, 14, 0, 0), 1, 79.25, 'Drachenblut Delikatessen', 'Walserweg 21', 'Aachen', '', '52066', 'Germany'), (10827, 'BONAP', 1, datetime.datetime(1998, 1, 12, 0, 0), datetime.datetime(1998, 1, 26, 0, 0), datetime.datetime(1998, 2, 6, 0, 0), 2, 63.54, "Bon app'", '12, rue des Bouchers', 'Marseille', '', '13008', 'France'), (10834, 'TRADH', 1, datetime.datetime(1998, 1, 15, 0, 0), datetime.datetime(1998, 2, 12, 0, 0), datetime.datetime(1998, 1, 19, 0, 0), 3, 29.78, 'Tradi�ao Hipermercados', 'Av. In�s de Castro, 414', 'Sao Paulo', 'SP', '05634-030', 'Brazil'), (10835, 'ALFKI', 1, datetime.datetime(1998, 1, 15, 0, 0), datetime.datetime(1998, 2, 12, 0, 0), datetime.datetime(1998, 1, 21, 0, 0), 3, 69.53, "Alfred's Futterkiste", 'Obere Str. 57', 'Berlin', '', '12209', 'Germany'), (10842, 'TORTU', 1, datetime.datetime(1998, 1, 20, 0, 0), datetime.datetime(1998, 2, 17, 0, 0), datetime.datetime(1998, 1, 29, 0, 0), 3, 54.42, 'Tortuga Restaurante', 'Avda. Azteca 123', 'M�xico D.F.', '', '5033', 'Mexico'), (10850, 'VICTE', 1, datetime.datetime(1998, 1, 23, 0, 0), datetime.datetime(1998, 3, 6, 0, 0), datetime.datetime(1998, 1, 30, 0, 0), 1, 49.19, 'Victuailles en stock', 